import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Carcio AI",
    description: "Generated by create next app",
};
interface LayoutProps {
    children: React.ReactNode;
    showFooter?: boolean;
}
export default function layout({
    children,
    showFooter = true
}: LayoutProps) {
    return (
        <div className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
            <main className="flex-grow">
                {children}
            </main>
            {showFooter && (
                <footer className="dark:bg-gray-900 text-white bg-blue-600 text-center p-4 justify-items-end z-0">
                    <p>
                        Tecnopuc Porto Alegre - Av. Ipiranga, 6681, Porto Alegre, Rio Grande do Sul, Brasil. CEP: 90619-900
                    </p>
                    <p>
                        2022 - {new Date().getFullYear()} Carcinocheck e Pipac Brasil - Todos os Direitos Reservados.
                    </p>
                </footer>
            )}
        </div>
    );
}