import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "../Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Carcio AI",
    description: "Generated by create next app",
};
interface LayoutProps {
    children: React.ReactNode;
    showFooter?: boolean;
}
export default function layout({
    children,
    showFooter = true
}: LayoutProps) {

    return (
        <div className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
            <main className="flex-grow">
                {children}
            </main>
            {showFooter && (
                <Footer />
            )}
        </div>
    );
}